#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Step 1: Build PTB-XL human-involved sample subset and initialize empty LLM schema.

This script performs two tasks:
1. Reads PTB-XL metadata from `ptbxl_database.csv`
2. Identifies machine-only samples using rule-based filtering
3. Keeps samples with human involvement
4. Generates:
   - a CSV file with the `machine_only_diagnosis` flag
   - a JSONL file for downstream LLM-based report parsing

Machine-only sample definition:
A sample is defined as "machine-only" only if ALL of the following hold:
    (1) validated_by is NaN
    (2) initial_autogenerated_report == True
    (3) validated_by_human != True

All remaining samples are treated as human-involved samples.

In the JSONL output:
- `ecg_id` is preserved from PTB-XL metadata
- `report` is copied from the original report field
- samples with empty reports are skipped
- an empty structured schema is initialized for llm1 / llm2 / llm3

Example:
    python src/step1_build_ptbxl_human_report_schema.py \
        --root_dir /path/to/ecg_preprocessing_pipeline

Expected input:
    {root_dir}/data/raw/ptbxl/ptbxl_database.csv

Outputs:
    {root_dir}/data/interim/ptbxl/ptbxl_database_with_machine_flag.csv
    {root_dir}/data/interim/ptbxl/ptbxl_human_report_empty_schema.jsonl
"""

from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
from typing import Any, Dict

import pandas as pd


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build PTB-XL human-involved subset and initialize empty report schema."
    )
    parser.add_argument(
        "--root_dir",
        type=str,
        required=True,
        help="Root directory of the ecg_preprocessing_pipeline project."
    )
    return parser.parse_args()


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def normalize_report_text(value: Any) -> str:
    """
    Convert report field to a clean string.
    Return empty string if the report is missing or invalid.
    """
    if pd.isna(value):
        return ""
    text = str(value).strip()
    if text.lower() in {"", "nan", "none", "null"}:
        return ""
    return text


def normalize_bool_like_series(series: pd.Series) -> pd.Series:
    """
    Normalize a boolean-like pandas Series into lowercase string form.

    Examples:
        True     -> "true"
        False    -> "false"
        NaN      -> "nan"
        "True"   -> "true"
        "FALSE"  -> "false"
    """
    return series.astype(str).str.strip().str.lower()


def build_empty_schema(ecg_id: int, report: str) -> Dict[str, Any]:
    """
    Create the empty JSON schema used for downstream LLM processing.
    """
    empty_label_block = {
        "report_cn": "",
        "report_label": {
            "raw": [],
            "mapped": [],
            "unmapped": []
        },
        "explicit": "",
        "uncertain": "",
        "historical": "",
        "old_MI": ""
    }

    item = {
        "ecg_id": int(ecg_id),
        "report": report,
        "llm1": copy.deepcopy(empty_label_block),
        "llm2": copy.deepcopy(empty_label_block),
        "llm3": {
            "final": copy.deepcopy(empty_label_block),
            "status": "",
            "reason": ""
        }
    }
    return item


def main() -> None:
    args = parse_args()
    root_dir = Path(args.root_dir).resolve()

    input_csv = root_dir / "data" / "raw" / "ptbxl" / "ptbxl_database.csv"
    output_dir = root_dir / "data" / "interim" / "ptbxl"
    output_csv = output_dir / "ptbxl_database_with_machine_flag.csv"
    output_jsonl = output_dir / "ptbxl_human_report_empty_schema.jsonl"

    ensure_dir(output_dir)

    if not input_csv.exists():
        raise FileNotFoundError(
            f"Input file not found: {input_csv}\n"
            f"Please place ptbxl_database.csv under:\n"
            f"{root_dir / 'data' / 'raw' / 'ptbxl'}"
        )

    # Read PTB-XL metadata
    df = pd.read_csv(input_csv)

    required_columns = [
        "ecg_id",
        "report",
        "validated_by",
        "initial_autogenerated_report",
        "validated_by_human",
    ]
    missing_columns = [col for col in required_columns if col not in df.columns]
    if missing_columns:
        raise ValueError(
            f"Missing required columns in ptbxl_database.csv: {missing_columns}"
        )

    # Normalize boolean-like columns for robust comparison across environments
    initial_autogenerated_report_norm = normalize_bool_like_series(
        df["initial_autogenerated_report"]
    )
    validated_by_human_norm = normalize_bool_like_series(
        df["validated_by_human"]
    )

    # Rule-based machine-only flag
    df["machine_only_diagnosis"] = (
        df["validated_by"].isna()
        & (initial_autogenerated_report_norm == "true")
        & (validated_by_human_norm != "true")
    )

    # Save CSV with the new flag
    df.to_csv(output_csv, index=False)

    # Print summary
    print("\n=== machine_only_diagnosis value counts ===")
    print(df["machine_only_diagnosis"].value_counts(dropna=False))
    print(f"\nMachine-only sample count: {int(df['machine_only_diagnosis'].sum())}")

    # Keep human-involved samples
    human_df = df[df["machine_only_diagnosis"] == False].copy()

    total_human_samples = len(human_df)
    written_count = 0
    skipped_empty_report = 0

    with open(output_jsonl, "w", encoding="utf-8") as f:
        for _, row in human_df.iterrows():
            ecg_id = row["ecg_id"]
            report = normalize_report_text(row["report"])

            if report == "":
                skipped_empty_report += 1
                continue

            item = build_empty_schema(ecg_id=ecg_id, report=report)
            f.write(json.dumps(item, ensure_ascii=False) + "\n")
            written_count += 1

    print("\n=== Output summary ===")
    print(f"Human-involved samples before empty-report filtering: {total_human_samples}")
    print(f"Skipped due to empty report: {skipped_empty_report}")
    print(f"Written to JSONL: {written_count}")
    print(f"\nSaved flagged CSV to: {output_csv}")
    print(f"Saved empty schema JSONL to: {output_jsonl}")


if __name__ == "__main__":
    main()